// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaUwK0RmZTCUOm6cFQuySjbV1HNiF40Zc',
    appId: '1:865097920786:web:2ea9e5f04b2be77e2ec3cb',
    messagingSenderId: '865097920786',
    projectId: 'receipt20260102',
    authDomain: 'receipt20260102.firebaseapp.com',
    storageBucket: 'receipt20260102.firebasestorage.app',
    measurementId: 'G-CEK9CQ6HL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ2yCHRPNq_nWYMvUhIzXZVx7PcCjbxVo',
    appId: '1:865097920786:android:018626fff7ad8ed32ec3cb',
    messagingSenderId: '865097920786',
    projectId: 'receipt20260102',
    storageBucket: 'receipt20260102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvH1Mh9jTB_BzvzVvl9R9S0l6hFC9XBEk',
    appId: '1:865097920786:ios:ae44ff5f7eb60f512ec3cb',
    messagingSenderId: '865097920786',
    projectId: 'receipt20260102',
    storageBucket: 'receipt20260102.firebasestorage.app',
    iosBundleId: 'com.example.receiptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvH1Mh9jTB_BzvzVvl9R9S0l6hFC9XBEk',
    appId: '1:865097920786:ios:ae44ff5f7eb60f512ec3cb',
    messagingSenderId: '865097920786',
    projectId: 'receipt20260102',
    storageBucket: 'receipt20260102.firebasestorage.app',
    iosBundleId: 'com.example.receiptApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaUwK0RmZTCUOm6cFQuySjbV1HNiF40Zc',
    appId: '1:865097920786:web:5454fe4fd106d4ef2ec3cb',
    messagingSenderId: '865097920786',
    projectId: 'receipt20260102',
    authDomain: 'receipt20260102.firebaseapp.com',
    storageBucket: 'receipt20260102.firebasestorage.app',
    measurementId: 'G-M0TNXQTR31',
  );

}